### ISSUE TITLE
Should the malware types open vocabulary become an enum

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#154] opened 2019-05-28 20:39 UTC
The malware type vocab now contains 22 items.  Do we feel that we have a complete set of types, such that we should make it an enumeration (close vocab).

``unknown`` was recently added.  Would this value be used for a type not among the 21 others?

**Comment by ejratl** [comment] 2019-05-28 21:20
This appears to be a duplicate of issue #153

**Closed** 2019-05-28 22:07 UTC
Labels: Status: Closed Duplicate, Target: STIX-2.1
