### ISSUE TITLE
Change external references to use a single string for hashes

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-stix2#36] opened 2017-10-25 17:55 UTC
At the very end of the 2.0 development and editorial process it was brought up that there was no way to verify the external references content that you were pointing to in the url field.  The TC decided that we should try and solve that for 2.0.  We noticed that we had this "hashes" type in cyber observables, so we just used that, without any real thought to the implementation.

The hashes type is a dictionary where the key is pulled from an open-vocab. As I have written a tool to handle this now, I have found it near impossible to do anything with this.  The problem comes from variability in the data. There is nothing you can count on.  As an implementer you will need to add library support for every known type of hashing algorithm that is in the open-vocab and then try to figure out what to do with something that is not in the open-vocab but that a user just adds.

This makes interoperability very painful and difficult.  It also adds enormous unnecessary complexity on code.  

I would like to propose that we make a breaking change, and change this to a "string" type and say in the description that the type for this release MUST be SHA256.

**Comment by johnwunder** [comment] 2017-10-25 18:59
I agree that this solution wasn't really ideal. I don't know that we need a breaking change for it, though we should consider all possibilities. Another option would be to add normative language encouraging the use of one hash, with an eventual eye towards requiring one hash.

**Comment by JasonKeirstead** [comment] 2017-10-25 19:03
I think the problem here is with the Hashes vocab itself, not this specific use.

The problem you raise will also be encountered with Artifact and File. If someone uses a custom hash, I have no way to do anything with it.

I think this might be a case where we elected for too much openness. What are the odds someone needs their own hash? The vocab here is already MASSIVE and arguably bigger than it needs to be. It should probably be a closed vocab.

**Comment by jordan2175** [comment] 2017-11-07 23:03
I really thing that we should just use a single hash for this one property.  The other option is to have two hash vocabs, one that is very minimal for things we do inside of STIX and one that is used when we need to document something that was hashed.

**Comment by gtback** [comment] 2017-11-08 21:17
I agree that standardizing on a single hash makes sense, since anyone who would need to use this should have access to the full content of the resource to calculate whatever hash we choose (I'm fine with SHA-256). I don't think this is worth making a breaking change in STIX 2.1, though, but would support normative text saying the `hashes` element SHOULD contain only one key/value pair, and what that key should be.

**Comment by JasonKeirstead** [comment] 2017-11-10 01:17
@gtback The problem is, as I mentioned above, we use hashes for possible validation in other places, such as Artifact and File. If we change it here we should be changing it everywhere.

**Comment by gtback** [comment] 2017-11-13 14:54
I'm all for forbidding custom Hash types everywhere (whether we want to do this in 2.1 or wait for a major version is debatable). My comment was regarding a specific use case: for external references, you SHOULD use only SHA-256 (for instance). 

IMO this is a reasonable restriction on external references (where you have the full content and can calculate/verify the hash yourself). Suggesting the use of only SHA-256 is probably not reasonable on File or Artifact.

**Comment by JasonKeirstead** [comment] 2017-11-14 15:54
@gtback I can kind of see the argument for File, but I don't understand how the external references case is any different from the Artifact case. It is the exact same thing... the purpose of the hash property on an artifact is to validate it.

**Comment by gtback** [comment] 2017-11-14 22:22
@JasonKeirstead:  You're right, I was forgetting that hashes on Artifact is to validate the content stored at a URL, not to provide a hash of the content already stored in payload_bin.

**Comment by jordan2175** [comment] 2017-11-14 23:21
We added this features in the days before we shipped 2.0 at John-Mark's request. We gave very little to no thought about it.  We said, "hey, cyber observables has this hashes-type thing, we can just re-use that" and we stuck it in.  This was in error. This property in the external references needs to be just a string type and we need to define in normative text that it is to use SHA256 for this release of STIX.

Regardless of it being a breaking change, we need to fix this. Lets please not force ourselves to live with this mistake until we do STIX 3.0

**Comment by gtback** [comment] 2017-11-15 22:47
>  This was in error

I agree

> we need to fix this

I disagree that this is worth breaking compatibility when we can instead define desired behavior via SHOULD requirements and interoperability standards.

**Comment by jordan2175** [comment] 2017-11-15 23:46
It is not about wanting to break comparability it is about doing it right.

Bret 

Sent from my Commodore 128D

PGP Fingerprint: 63B4 FC53 680A 6B7D 1447  F2C0 74F8 ACAE 7415 0050

**Comment by gtback** [comment] 2017-11-16 14:43
Just because we agree it would be better if it were different doesn't mean it's worth changing, especially if it means breaking compatibility in a version where we aren't supposed to break compatibility (more than necessary, at least).

**Comment by jordan2175** [comment] 2018-01-08 18:39
STIX 2.0 is an MVP first pass.  It was never meant to be a set in stone never fix things or have a breaking change.  Further, it is only a CS, it is not yet an OASIS Standard.

**Comment by allant0** [comment] 2018-01-23 02:41
Given that many hash algorithms exist and are in common use and wont change overnight I dont see how we can change to only SHA256. If I understand correctly what Bret is asking for is the following change:

"external_references": [
{
"source_name": "veris",
"external_id": "0001AA7F-C601-424A-B2B8-BE6C9F5164E7",
"url": "https://github.com/vz-risk/VCDB/blob/master/data/json/0001AA7F-C601-424A-B2B8-
BE6C9F5164E7.json",
"hashes": {
"SHA-256": "6db12788c37247f2316052e142f42f4b259d6561751e5f401a1ae2a6df9c674b"
}
}
],

to

"external_references": [
{
"source_name": "veris",
"external_id": "0001AA7F-C601-424A-B2B8-BE6C9F5164E7",
"url": "https://github.com/vz-risk/VCDB/blob/master/data/json/0001AA7F-C601-424A-B2B8-
BE6C9F5164E7.json",
"hashes": [ "6db12788c37247f2316052e142f42f4b259d6561751e5f401a1ae2a6df9c674b"
]
}
],

where the hashes property changes to a specific list of SHA256 hashes.

How about this instead?

Change to 

hashes_sha256: [ <sha256_hash> ]
hashes_md5: [ <md5_hash> ]
hashes_sha1: [ <sha1_hash> ]
and so on.

That way you introduce property support with specific type information in the property itself.

If there's a new custom hash then that could be introduced first of all as a custom property that could then be embraced as part of the standard if its widely adopted.

**Comment by jordan2175** [comment] 2018-01-23 03:54
What I was suggesting is just do:

`"external_references": [
{
    "source_name": "veris",
    "external_id": "0001AA7F-C601-424A-B2B8-BE6C9F5164E7",
    "url": "https://github.com/vz-risk/VCDB/blob/master/data/json/0001AA7F-C601-424A-B2B8-
BE6C9F5164E7.json",
    "hash": "6db12788c37247f2316052e142f42f4b259d6561751e5f401a1ae2a6df9c674b"
}
],`

**Comment by wbolster** [comment] 2018-01-23 10:53
for inspiration:

``` json
{
  "...": "...",
  "hashes": [
    "sha256:abcdef...",
    "sha512:abcdef...",
    "..."
  ]
}
```

this allows for future extensions, and has _fixed_ json keys and a flat structure (very convenient in lots of software, e.g. elasticsearch and many json/object mappers).

**Comment by jordan2175** [comment] 2018-01-23 20:56
We discussed this on the working call on 2018-01-23 and the consensus on the call was that we need to address/fix this for 2.1, however, we did not come to an agreement on how to fix it.  We identified 2-3 ways that this could be fixed.  1) change to just a string, 2) make individual properties for the hash that is used in the specific version, 3) add normative text that calls out the hash that MUST be used, if one is used.  Basically keep the dictionary but define a single entry that is used in this context.  Jason also brought up that we need to fix this for the artifact object as well.

**Comment by jmgnc** [comment] 2018-01-26 00:29
IMO, keep it as is, and add language about what hash function SHOULD be used.  As I said on the call, we should not require certain hash implementations, as other governments may require different algorithms to be used.  This is an interoperability issue, and can be solved there as well instead of in the spec.

I tried to get a recommended hash function language into the spec but it was rejected. I couldn't even get a recommendation of what hashes NOT to use!

Keeping the dictionary does allow easier transition to new hashes.

Switching to a list, where it's indexed by the start of the string is just a poor man's dictionary, and should not be used.  We have key/value pairs as part of the language, we should use them.

**Comment by jordan2175** [comment] 2018-01-30 00:48
So long as we say that it is not just mandatory to implement, but it is mandatory to include.  If a trust group wants to do things above and beyond, fine.  But we need something that is "defined" for STIX 2.x.

**Comment by johnwunder** [comment] 2018-02-23 20:53
I feel like having our preferred hash as mandatory to include/implement but leave the option for additional ones makes the most sense. FWIW though we could also make it a SHOULD rather than a MUST.

**Comment by allant0** [comment] 2018-02-23 21:01
suggest making a new property for SHA256_hash and mark 'hashes' as obsolete/deprecated. a) this introduces explicit type and singke hash and avoids breaking change problem

**Comment by johnwunder** [comment] 2018-02-23 21:10
That's a good idea. Those wanting to use other hashes can use custom properties and then it's very clear that they're doing something custom that may not be supported.

I would recommend either just removing the hashes property and accepting that it's a breaking change or having a policy where after one minor release of a property being deprecated we remove it. I wouldn't want these old deprecated things hanging around for forever, it becomes technical debt in the standard.

**Comment by jmgnc** [comment] 2018-02-23 22:24
problem w/ @allant0 's suggestion is that there is no 'standard' custom property for other things, like sha512, or sha3, etc. which means that when people implement other hashes, there is incompatibilities between these.

What happens when sha256 is broken, and people are required to move to sha3?  Instead of simply adding sha3 to the dictionary of hashes, we now have to standardize the property and it will significantly delay dealing w/ a broken hash.  This means that the CTI TC has to issue a new standard w/ the properties before it can be used, or we might have implementations using different custom properties for the new hash, etc.

**Comment by jordan2175** [comment] 2018-02-24 01:32
I agree with @allant0 The best solution is to just accept the breaking change and have a nice clean separation.  No one has implemented this yet, as it is currently not implementable.  So the risk to products and current development is really really low.  

To address John-Mark's concerns, if and when sha256 gets broken, we will probably be on STIX 3.0 by then. To often we try to overly future proof things, and we learned from STIX 1.x that, that was a mistake. Lets just make it super easy for people to implement now, and worry about any changes in the future.

**Comment by ikiril01** [comment] 2018-02-26 17:41
I'm fine with going with a single hash/property as a solution to this issue. SHA-256 is a good candidate as its use is fairly standardized.

**Comment by treyka** [comment] 2018-02-27 15:03
I take issue with this bit of @jordan2175's initial comment:

```The problem comes from variability in the data. There is nothing you can count on. As an implementer you will need to add library support for every known type of hashing algorithm that is in the open-vocab and then try to figure out what to do with something that is not in the open-vocab but that a user just adds.```

The fact is that 99% of the time it's going to be MD5, SHA-1, SHA-256, or SHA-512. (@jmgnc of course, no-one **should** still be using MD5 and SHA-1, but a lot of people **are** and we can't change that fact.) I don't think there's anything in the spec that says, "As an implementer, you have implement support for every type of hashing algorithm in the open vocab." The spec **certainly** doesn't say that if as a producer I send you as a consumer some STIX with an imaginary hashing algorithm `foobar-8192` in the open vocab that you should do anything but drop data which you cannot process on the floor and log an error.

Rather than deprecating the hashing-algo type, we can add a single sentence saying that for external references and artifacts implementers **SHOULD** use SHA-256, unless there's a compelling reason otherwise.

Seriously, we have *way* more pressing issues than this one. Let's just add the clarifying sentence and stop burning precious cycles on this non-issue.

**Comment by ikiril01** [comment] 2018-02-27 15:10
@treyka good point - if we make SHA-256 as the default (SHOULD) algorithm, we can re-use our existing `hashes` type and make it more useful in other places as well. That makes more sense to me than trying to introduce a new property to do the same thing.

**Comment by johnwunder** [comment] 2018-02-27 15:20
I'm fine with adding a statement saying you SHOULD use SHA256. I think interop could also test for that for the relevant tests (if any).

**Comment by johnwunder** [comment] 2018-02-27 21:12
This was discussed on the Feb 27 working call and the consensus was to make a SHOULD statement to recommend a hash, likely SHA256. This was a split vote, with 11 voting for that option and 4 voting for the suggestion from @allant0. Notes from the call can be found here: https://www.oasis-open.org/committees/document.php?document_id=62614&wg_abbrev=cti.

**Comment by johnwunder** [comment] 2018-04-25 13:58
I added the text "To achieve best compatibility, the SHA-256 hash SHOULD be used whenever possible." to section 2.6 in Part 1 in suggest mode. Can one of the editors review and accept? When that's done we can close this issue.

**Closed** 2018-04-25 16:03 UTC
Labels: F2F, Phase: 3-Final Review, STIX: Core-objects, Type: Enhancement
