### ISSUE TITLE
Reason for TLPs having specific object instance definitions?!

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#152] opened 2019-05-10 20:17 UTC
In the Core Concepts section 4.1.4 it outlines that:

>The following standard marking definitions MUST be used to reference or represent TLP markings. Other instances of tlp-marking MUST NOT be used (the only instances of TLP marking definitions permitted are those defined here).

with specific instances of the objects...

Why was this done?  Why is the TLP object so restricted?  This seems to be a HUGE limitation, meaning that custom fields are not possible to be added.

The use of the TLP values (white, green, amber, red) are unique in themselves, so what is the reason for locking this entire object type to specific instances with IDs and created dates, etc...

**Comment by jordan2175** [comment] 2019-05-23 14:32
The idea was that the TLP markings are so commonly used and used in their vanilla form that we did not want thousands of different versions of TLP:Green or TLP:Red.  The idea was to give them an ID in the STIX spec that people could use.  This would greatly improve interoperability for the most common form of marking.  If you want to use a TLP like marking but with extra information, you can create your own marking type.  Right now the text does not talk about it, and we will try and address that.  Several .gov group already do this.

**Comment by StephenOTT** [comment] 2019-05-23 14:47
This seems like it should be like a common impl of the objects (like how we have a common impl of kill chain stages)

Seems like a big waste of a entire entity to lock it down and force a x- entity to be created

**Comment by cobsec** [comment] 2019-07-22 15:21
+1 to Stephen's point on this. Agree that the current wording in the stix2 spec seems to only allow a subset of the functionality that the description of the TLP provides. Understand the reasoning behind having a central library of the common TLP markings, but feel we should at least ease the restrictions on the language to allow for customisation to implement the full range of TLP functionality.

TLP description is deliberately vague to allow users to decide a distribution list on-transmission of the data. The stix2 spec as-written prohibits any such user decisions to be reflected in the data markings without creating TLP "rip-offs". Suggest loosening the language to allow users to build on the provided library entities.

Interesting idea from Rich P that I implemented as a custom object type that inherits the core TLP library objects but provides the means to do named distribution:
```
from stix2.v21 import CustomMarking
from stix2.properties import ListProperty, ReferenceProperty

@CustomMarking('x-tlpplus-marking', [
    ('tlp_marking_def_ref', ReferenceProperty(
        type='marking-definition', required=True)),
    ('distribution_refs', ListProperty(
        ReferenceProperty(type='identity'), required=True)),
])
class TLPPlusMarking(object):
    pass
```
Would the above be 'specification compliant' with the current wording?

**Comment by rpiazza** [comment] 2019-07-22 16:10
@cobsec,

What I suggested, and you implemented, was a stop-gap solution.  Jason and Allan are correct that you should bring up your suggestions to FIRST.  IEP is a data marking they are proposing to "improve upon" TLP.  Here is a link to the IEP website if you need it: https://www.first.org/global/sigs/iep/

**Comment by StephenOTT** [comment] 2019-07-22 17:38
I am still confused on the underpinning logic of a TLP entity that is only for 4 instances...

TLP values (colours) are enum values. If the impl of TLP was to conform to a standard or cert then that would be fully available between the producers and consumers within a trust group.  This is like defining what goes into the Kill chain values. 

And even if you wanted to have a single instances you could create the equivalent of a closed vocab of TLP objects which are the current 4 objects, and he spec states that the STIX community has chosen to support these 4 instances (with their UUIDs) as the official instances of TLP impl.  

Having the restriction that TLP can ONLY be used for the 4 instances seems to be a unique constraint in the spec, and there are other features of the spec that have similar impl without the need for this large constraint.  

If vendors are going to validate the TLP instances against the 4 official TLPs then there is no real concern of many TLP versions floating around.  The workaround suggested is just a further layer of complexity.  If the restriction that "TLP entity can only be used for the 4 official instances" is removed, and it is stated in the TLP section of the spec that the 4 official TLP instances are blah blah blah and blah, then this continues the usage of having official TLP instances, AND it allows further usage scenarios by other vendors and producers/consumers.  

Interop testing can validate that a producer/consumer validates the official TLP versions vs allowing non-officials TLP versions.

**Comment by rpiazza** [comment] 2019-07-22 19:00
Hi @StephenOTT,
What you state in the third paragraph is basically what we did - except vocabulary entries aren't objects - so I'm not sure what you are thinking when you say "could create the equivalent of a closed vocab of TLP objects"

We essentially created 4 marking definition instances, which according to the spec, exist "a priori".  To implement the spec, you would probably want to pre-populate your data store with these 4 instances.

The only thing we are trying to do here is to cut down on the necessity to ever "share" TLP data marking _instances_.  According to the spec, every product that is implemented MUST "know" about these instances, given their id reference.  Therefore there is never a reason to share them.

You don't get much with TLP markings - they are purposefully very vague.  The trust group one is a part of could define and agree upon extra requirements on, say TLP:AMBER - but that is not part of the TLP marking definition.

**Comment by StephenOTT** [comment] 2019-07-22 20:08
I agree with your points. But they do not address why the restriction to not create further TLP instances should exist.  Why have to force the creation of a custom entity?   Have have the defined "official" TLP instances, which is enough to validate against.  The restriction does not prevent many different TLPs floating around.  It just creates a scenario where people create a custom entity which is a duplicate of TLP.  

If the restriction is removed, you still get the official TLP instances and we don't have custom TLP entities having to be created, and we can use x_ fields on TLP for the non-official instances to further refine TLP.  It's a win all around.

**Comment by cobsec** [comment] 2019-07-23 07:29
Indeed, the issue is not that I don't think TLP standard objects should _exist_ in the spec, simply that the wording around them prohibiting any customisation / other versions of TLP is unnecessarily prohibitive and actually prevents implementers from 'doing TLP properly' should they wish.

The policy that every recipient 'should know' about the core, defined TLP objects is totally fine - perhaps we can be explicit on that requirement and allow implementers that want or need to do anything more sophisticated (which may require custom entities and/or fields) figure out how they can do that and still support the base objects.

**Comment by StephenOTT** [comment] 2019-07-24 14:26
Could we reopen this issue?

**Comment by rpiazza** [comment] 2019-07-24 16:49
Of course.  I will re-open the issue, but for future reference, you could have done that yourself :-)

**Comment by StephenOTT** [comment] 2019-07-24 16:52
@rpiazza The issues cannot be reopened by non-members of the org/repo.

https://github.com/isaacs/github/issues/583

**Comment by rpiazza** [comment] 2019-07-24 17:21
I stand corrected.  I thought you were a member.

**Comment by StephenOTT** [comment] 2019-08-18 18:05
Should this be reopened for discussion as part of public review of 2.1?  

@rpiazza the tags on this issue appears to be out of date as well.

**Comment by jordan2175** [comment] 2019-08-19 23:36
@StephenOTT @rpiazza The way to reopen issues is to bring the issue up on the list or during a working call and get enough people to agree to do this.  

Keep in mind that this was one of the first things that was done in STIX 2.0, so going back and removing this or changing it might be hard for people to accept.  There was a lot of debate around this, and this is what was settled upon.  Also, we recently had a long debate about adding description to data markings so people could add this and there was significant consensus against doing that.

I am all for giving you time to discuss, but you will need to show consensus wants to change this.  I would also propose giving exact wording changes.  So I would probably put together some slides that talk through the problem and give exact concrete changes you would like to see. Then request time from @ejratl and myself for a future working call. So I am closing this again, until such a time that the TC as a whole suggests that we make a change.

**Closed by jordan2175** 2019-08-19 23:36 UTC
Labels: STIX: Core, Status: Closed Done, Target: STIX-2.1, Type: Question
