### ISSUE TITLE
Provide a Regex for allowed Granular Expression operator usage

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#126] opened 2018-12-19 18:14 UTC
Provide a Regex for allowed Granular Expression operator usage.

**Comment by ejratl** [comment] 2019-05-06 15:05
@StephenOTT I don't understand this suggestion. Can you provide more context as to the document section it applies to and how it would be used, please?

**Comment by StephenOTT** [comment] 2019-05-06 15:55
There are multiple areas In the spec where there are rules outlined. Would be helpful to impl if the common regex expressions were provided rather than. Each impl doing the reinvention.  Granular markings have specific values allowed (similar to Json path but not the exact spec). This was a example of a space where having the regex provided would be helpful.

**Comment by jordan2175** [comment] 2020-02-12 21:12
This is a duplicate of 119, closing.

**Closed by jordan2175** 2020-02-12 21:12 UTC
Labels: Phase: 1-Need to Discuss, STIX: Core, Target: Unknown, Type: Enhancement
