### ISSUE TITLE
Mismatch between common property "lang" and software property "languages.

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#226] opened 2020-04-01 17:25 UTC
The common property "lang" has the following description:

>The lang property identifies the language of the text content in this object. When present, it MUST be a language code conformant to [RFC5646]. If the property is not present, then the language of the content is en (English).

The software property languages  has the follow description:

>Specifies the languages supported by the software. The value of each list member MUST be an ISO 639-2 language code [ISO639-2].

These two language standards are slightly different.  The problem is that the basic form of RFC5646 is 2 characters, and the basic form of ISO639-2 is 3 characters.  

To avoid confusion, we should pick one standard for all language properties - preferably RFC5646, because two characters is more commonly used than three characters.

**Comment by ejratl** [comment] 2020-05-20 21:35
This is a duplicate of #227 (just with a typo that 227 doesn't have).

**Closed by ejratl** 2020-05-20 21:35 UTC
